title: Garrett Bull <br> Masters of Cybersecurity and Information Assurance
tagline: Cybersecurity specialist working to simplify cybersecurity for small businesses
description: GRC and Cyber Operations Specialist | HITRUST | Linux+ | PenTest+ |  CASP+ |
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
google_analytics: G-E9F75MH8RN
