title: Garrett Bull | Masters of Cybersecurity and Information Assurance
tagline: Cybersecirty Specialist simplifying information security
description: GRC and Cyber Operations Manager | HITRUST | CASP+ | Linux+ | PenTest+ |
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
plugins: jekyll-remote-theme
google_analytics: G-E9F75MH8RN
