title: "Garrett Bull"
tagline: "Masters of Cybersecurity and Information Assurance"
description: GRC and Cyber Operations Specialist | HITRUST | Linux+ | PenTest+ |  CASP+ |
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
google_analytics: G-E9F75MH8RN
