title: Garrett Bull<br>Masters of Cybersecurity and Information Assurance
tagline: Cybersecirty Specialist simplifying information security
description: GRC and Cyber Operations Manager | HITRUST | Linux+ | PenTest+ |  CASP+ |
[LinkedIn](https://www.linkedin.com/in/garrettbull/) | [Credily](https://www.credly.com/users/garrettbull)
markdown: kramdown
remote_theme: pages-themes/midnight@v0.2.0
google_analytics: G-E9F75MH8RN
